services:
  django_db_test:
    container_name: django_db_test
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_USER=django_test
      - POSTGRES_PASSWORD=django_test
      - POSTGRES_DB=django_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U django_test"]
      interval: 5s
      timeout: 5s
      retries: 5

  django_web_test:
    container_name: django_web_test
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - POSTGRES_NAME=django_test
      - POSTGRES_USER=django_test
      - POSTGRES_PASSWORD=django_test
      - POSTGRES_HOST=django_db_test
      - POSTGRES_PORT=5432
      - FORCE_COLOR=1
    env_file:
      - .env
    volumes:
      - ./src:/app
    depends_on:
      django_db_test:
        condition: service_healthy
    command: ["./entry_test.sh"]

networks:
  default:
    driver: bridge
